import {
  FaLaptop,
  FaMobileAlt,
  FaTshirt,
  FaCouch,
  FaAppleAlt,
  FaShoppingBag,
  FaBlender,
  FaPaintRoller,
  FaShoePrints,
  FaMotorcycle,
  FaHeart,
  FaTabletAlt,

  FaSun,
  FaCar,
  FaGlasses,
  FaRing,
  FaUserTie,
  FaFemale,
  FaWatchmanMonitoring,
} from 'react-icons/fa'

import { IconType } from 'react-icons'

export const categoryIcons: Record<string, IconType> = {
  beauty: FaHeart,
  fragrances: FaSun,
  furniture: FaCouch,
  groceries: FaAppleAlt,
  'home-decoration': FaPaintRoller,
  'kitchen-accessories': FaBlender,
  laptops: FaLaptop,
  'mens-shirts': FaUserTie,
  'mens-shoes': FaShoePrints,
  'mens-watches': FaWatchmanMonitoring,
  'mobile-accessories': FaMobileAlt,
  motorcycle: FaMotorcycle,
  'skin-care': FaHeart,
  smartphones: FaMobileAlt,
  'sports-accessories': FaShoppingBag,
  sunglasses: FaGlasses,
  tablets: FaTabletAlt,
  tops: FaTshirt,
  vehicle: FaCar,
  'womens-bags': FaShoppingBag,
  'womens-dresses': FaFemale,
  'womens-jewellery': FaRing,
  'womens-shoes': FaShoePrints,
  'womens-watches': FaWatchmanMonitoring,
}
